"""Add category type

Revision ID: 210c0e105d2c
Revises: 5e142dc66d48
Create Date: 2026-08-24 22:20:03.438998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210c0e105d2c'
down_revision = '5e142dc66d48'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.String(length=10), nullable=True)
        )

    op.execute(
        "UPDATE categories SET type = 'expense' WHERE type IS NULL"
    )

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.String(length=10),
            nullable=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
